### ISSUE TITLE
How to clone and use in Kali Linux system

### ISSUE THREAD

**Issue by yeyi9** [D4Vinci/PyFlooder#14]
How to clone and use in Kali Linux system

**Comment by somerandomguy404** [comment]
1/type sudo apt install git  2/ type git clone and the link of the project you whant to clone
3/after installing type ls 4/then type cd and the name of the project you whant to run 
5/try to find in what language is the code written is in says name.sh then to run it type bash name.sh if name.py python name.py
your done
